puppet module install puppetlabs-ruby
puppet module install jgoettsch/mercurial
puppet module install puppetlabs/apache
puppet module install puppetlabs/postgresql
puppet module install puppetlabs/rsync
puppet module install maestrodev/wget
puppet module install glarizza-pick
puppet module install camptocamp-archive
puppet module install puppetlabs-java
puppet module install stahnma-epel
